window.App = window.App || {};

App.events = {
  getNextEventSlot() {
    const now = new Date();
    const currentHour = now.getHours() + now.getMinutes() / 60 + now.getSeconds() / 3600;
    const nextHourToday = App.config.eventSlots.find(hour => hour > currentHour);
    const next = new Date(now);

    if (nextHourToday !== undefined) next.setHours(nextHourToday, 0, 0, 0);
    else {
      next.setDate(next.getDate() + 1);
      next.setHours(App.config.eventSlots[0], 0, 0, 0);
    }

    return next;
  },

  updateEventCountdown() {
    const element = document.getElementById("nextEventCountdown");
    if (!element) return;
    const diff = Math.max(0, App.events.getNextEventSlot() - new Date());
    const hours = Math.floor(diff / 3600000);
    const minutes = Math.floor((diff % 3600000) / 60000);
    const seconds = Math.floor((diff % 60000) / 1000);
    element.textContent = `${String(hours).padStart(2, "0")}h ${String(minutes).padStart(2, "0")}m ${String(seconds).padStart(2, "0")}s`;
  },

  getCurrentEventSlotKey() {
    const now = new Date();
    const currentHour = now.getHours();
    const openedSlot = [...App.config.eventSlots].reverse().find(hour => hour <= currentHour);
    if (openedSlot === undefined) return "before-first-slot";
    return `${now.toISOString().slice(0, 10)}-${openedSlot}`;
  },

  async autoGenerateDueEvents() {
    const currentHour = new Date().getHours();
    const hasOpenedSlot = App.config.eventSlots.some(hour => hour <= currentHour);
    if (!hasOpenedSlot || App.state.autoEventGenerationRunning) return;

    const slotKey = App.events.getCurrentEventSlotKey();
    if (slotKey === App.state.lastAutoEventCheckKey) return;

    App.state.autoEventGenerationRunning = true;
    App.state.lastAutoEventCheckKey = slotKey;

    try {
      const data = await App.api.postToApi({ action: "generateDueEvents" });
      if (data.ok && Number(data.created || 0) > 0) {
        App.utils.setMessage(document.getElementById("eventsMessage"), data.message || "Eventos automáticos gerados.", "success");
        await App.api.loadApiData({ showLoader: false });
      }
    } catch (error) {
      console.warn("Falha ao gerar eventos automaticamente", error);
    } finally {
      App.state.autoEventGenerationRunning = false;
    }
  },

  getEventTypeClass(event) {
    const value = Number(event.ImpactoFinanceiro || 0);
    if (value > 0) return "positive";
    if (value < 0) return "negative";
    return "neutral";
  },

  getEventImpactLabel(event) {
    const value = Number(event.ImpactoFinanceiro || 0);
    if (value === 0) return event.Efeito || "Sem impacto financeiro";
    return value > 0 ? `+${App.utils.formatCurrency(value)}` : `-${App.utils.formatCurrency(Math.abs(value))}`;
  },

  getEventDurationLabel(event) {
    const durationType = App.utils.normalizeText(event.DuracaoTipo || "");
    const affectedPlayer = String(event.JogadorAfetado || "").trim();
    const durationValue = Number(event.DuracaoValor || 0);
    const remainingMatches = Number(event.PartidasRestantes || durationValue || 0);
    const expiresAt = event.ExpiraEm ? new Date(event.ExpiraEm) : null;

    if (!affectedPlayer && !durationType && !event.ExpiraEm) return "";

    if (durationType.includes("partida")) {
      return `${affectedPlayer ? `${affectedPlayer}: ` : ""}${remainingMatches} partida(s) restante(s)`;
    }

    if (expiresAt && !Number.isNaN(expiresAt.getTime())) {
      const diff = Math.max(0, expiresAt - new Date());
      const hours = Math.floor(diff / 3600000);
      const minutes = Math.floor((diff % 3600000) / 60000);
      return `${affectedPlayer ? `${affectedPlayer}: ` : ""}${String(hours).padStart(2, "0")}h ${String(minutes).padStart(2, "0")}m restantes`;
    }

    if (durationValue) return `${affectedPlayer ? `${affectedPlayer}: ` : ""}${durationValue} ${event.DuracaoTipo || "unidade(s)"}`;
    return affectedPlayer ? `${affectedPlayer} afetado` : "";
  },

  getActiveEventsForBuyer(buyer) {
    return App.state.apiEvents.filter(event =>
      App.utils.normalizeText(event.Jogador) === App.utils.normalizeText(buyer) &&
      ["aplicado", "ativo", "gerado"].includes(App.utils.normalizeText(event.Status))
    );
  },

  renderActiveInjuriesForBuyer(buyer) {
    const injuries = App.events.getActiveEventsForBuyer(buyer).filter(event => String(event.JogadorAfetado || "").trim());
    if (!injuries.length) return "";

    return `
      <p class="legend-title" style="margin-top:12px;">Jogadores afetados</p>
      <ul class="player-list">
        ${injuries.slice(0, 4).map(event => `<li>${event.JogadorAfetado} — ${App.events.getEventDurationLabel(event)}<br><span class="calendar-muted">${event.Titulo || "Evento ativo"}</span></li>`).join("")}
      </ul>
    `;
  },


  getEventDateTime(event) {
    const dataText = String(event.Data || "").replace(/^'/, "").trim();
    const horaText = String(event.Horario || "").replace(/^'/, "").trim();

    if (/^\d{2}\/\d{2}\/\d{4}$/.test(dataText)) {
      const [day, month, year] = dataText.split("/").map(Number);
      const [hour = 0, minute = 0] = /^\d{2}:\d{2}$/.test(horaText)
        ? horaText.split(":").map(Number)
        : [0, 0];

      return new Date(year, month - 1, day, hour, minute, 0, 0);
    }

    const timestamp = new Date(event.Timestamp || event.ExpiraEm || 0);
    if (!Number.isNaN(timestamp.getTime())) return timestamp;

    return new Date(0);
  },

  getEventSlotKey(event) {
    const date = App.events.getEventDateTime(event);

    if (Number.isNaN(date.getTime())) {
      return "";
    }

    const yyyy = date.getFullYear();
    const mm = String(date.getMonth() + 1).padStart(2, "0");
    const dd = String(date.getDate()).padStart(2, "0");
    const hh = String(date.getHours()).padStart(2, "0");

    return `${yyyy}-${mm}-${dd}-${hh}`;
  },

  isActiveOrDurationEvent(event) {
    const status = App.utils.normalizeText(event.Status);
    const hasDuration = Boolean(event.ExpiraEm || event.DuracaoTipo || event.JogadorAfetado);
    const expiresAt = event.ExpiraEm ? new Date(event.ExpiraEm) : null;
    const stillInTime = expiresAt && !Number.isNaN(expiresAt.getTime()) ? expiresAt >= new Date() : false;
    const remainingMatches = Number(event.PartidasRestantes || 0);

    return status === "ativo" || stillInTime || remainingMatches > 0 || (hasDuration && status !== "encerrado");
  },

  getLatestEventSlotKey(events) {
    const keys = events
      .map(event => App.events.getEventSlotKey(event))
      .filter(Boolean)
      .sort();

    return keys.length ? keys[keys.length - 1] : "";
  },

  getFilteredEvents() {
    const search = App.utils.normalizeText(document.getElementById("eventsSearchInput")?.value);
    const owner = document.getElementById("eventsOwnerFilter")?.value || "all";
    const type = document.getElementById("eventsTypeFilter")?.value || "all";
    const period = document.getElementById("eventsPeriodFilter")?.value || "latest";

    let events = [...App.state.apiEvents];
    if (period === "latest") {
      const latestKey = App.events.getLatestEventSlotKey(events);
      events = latestKey ? events.filter(event => App.events.getEventSlotKey(event) === latestKey) : events;
    } else if (period === "active") {
      events = events.filter(event => App.events.isActiveOrDurationEvent(event));
    } else if (period === "today") {
      const todayText = new Date().toLocaleDateString("pt-BR");
      events = events.filter(event => App.events.formatEventDate(event.Data || event.Timestamp) === todayText);
    }

    events = events
      .filter(event => owner === "all" || event.Jogador === owner)
      .filter(event => type === "all" || App.events.getEventTypeClass(event) === type)
      .filter(event => {
        if (!search) return true;
        return App.utils.normalizeText(`${event.Jogador} ${event.Titulo} ${event.Descricao} ${event.Efeito} ${event.Tipo} ${event.JogadorAfetado}`).includes(search);
      })
      .sort((a, b) => App.events.getEventDateTime(b) - App.events.getEventDateTime(a));

    if (period === "last12") {
      events = events.slice(0, 12);
    }

    return events;
  },


  formatEventDate(value) {
    if (!value) return "";
    const text = String(value || "").replace(/^'/, "").trim();
    if (/^\d{2}\/\d{2}\/\d{4}$/.test(text)) return text;
    const date = new Date(text);
    if (!Number.isNaN(date.getTime())) return date.toLocaleDateString("pt-BR");
    return text;
  },

  formatEventTime(value) {
    if (!value) return "";
    const text = String(value || "").replace(/^'/, "").trim();
    if (/^\d{2}:\d{2}$/.test(text)) return text;
    const date = new Date(text);
    if (!Number.isNaN(date.getTime()) && date.getFullYear() < 2000) {
      return date.toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" });
    }
    return text;
  },

  cleanEventEffect(event) {
    const effect = String(event.Efeito || "").trim();
    if (effect && effect !== "#ERROR!") return effect;

    const modifier = Number(event.ModificadorTransferencias || 0);
    if (modifier > 0) return `Libera ${modifier} transferência(s) extra hoje.`;
    if (modifier < 0) return `Reduz ${Math.abs(modifier)} transferência(s) hoje.`;

    return "Sem efeito adicional.";
  },

  render() {
    App.events.updateEventCountdown();

    const summary = document.getElementById("eventsSummary");
    const grid = document.getElementById("eventsGrid");
    if (!summary || !grid) return;

    const todayText = new Date().toLocaleDateString("pt-BR");
    const todayEvents = App.state.apiEvents.filter(event => App.events.formatEventDate(event.Data || event.Timestamp) === todayText);
    const totalImpact = App.state.apiEvents.reduce((sum, event) => sum + Number(event.ImpactoFinanceiro || 0), 0);
    const pendingSlots = Math.max(0, (App.config.eventSlots.length * App.utils.getHumanBuyers().length) - todayEvents.length);

    summary.innerHTML = `
      <article class="summary-card"><span>Eventos hoje</span><strong>${todayEvents.length}</strong></article>
      <article class="summary-card"><span>Faltam hoje</span><strong>${pendingSlots}</strong></article>
      <article class="summary-card"><span>Impacto total</span><strong>${App.utils.formatCurrency(totalImpact)}</strong></article>
      <article class="summary-card"><span>Horários</span><strong>05h-23h</strong></article>
    `;

    const events = App.events.getFilteredEvents();
    const periodSelect = document.getElementById("eventsPeriodFilter");
    const periodLabel = periodSelect ? periodSelect.options[periodSelect.selectedIndex]?.textContent : "Eventos filtrados";

    grid.innerHTML = events.length ? `
      <div class="compact-info-card">
        <strong>${events.length} evento(s) exibido(s)</strong>
        <span>${periodLabel}. Use os filtros para consultar eventos antigos quando precisar.</span>
      </div>
    ` + events.map(event => {
      const typeClass = App.events.getEventTypeClass(event);
      const color = App.data.ownerColors[event.Jogador] || App.data.ownerColors["Livre / CPU"];
      const modifier = Number(event.ModificadorTransferencias || 0);
      return `
        <article class="event-card" style="--event-color:${color}">
          <div class="event-card-header">
            <div><h2>${event.Titulo || "Evento"}</h2><span class="owner" style="background:${color}">${event.Jogador || "Liga"}</span></div>
            <span class="event-impact ${typeClass}">${App.events.getEventImpactLabel(event)}</span>
          </div>
          <p>${event.Descricao || "Sem descrição."}</p>
          <p><strong>Efeito:</strong> ${App.events.cleanEventEffect(event)}</p>
          ${modifier !== 0 ? `<span class="limit-pill">${modifier > 0 ? "+" : ""}${modifier} transferência(s) hoje</span>` : ""}
          ${event.JogadorAfetado ? `<span class="injury-pill">${event.JogadorAfetado} afetado</span>` : ""}
          ${App.events.getEventDurationLabel(event) ? `<div class="event-timer"><strong>Duração do efeito</strong>${App.events.getEventDurationLabel(event)}</div>` : ""}
          <div class="event-meta">${App.events.formatEventDate(event.Data)} · ${App.events.formatEventTime(event.Horario)} · ${event.Tipo || "Evento"} · ${event.Status || "Gerado"}</div>
        </article>
      `;
    }).join("") : `<article class="event-card"><h2>Nenhum evento encontrado</h2><p>Troque o filtro de período para ver eventos anteriores ou o histórico completo.</p></article>`;
  }
};
