window.App = window.App || {};

App.events = {
  getNextEventSlot() {
    const now = new Date();
    const currentHour = now.getHours() + now.getMinutes() / 60 + now.getSeconds() / 3600;
    const nextHourToday = App.config.eventSlots.find(hour => hour > currentHour);
    const next = new Date(now);

    if (nextHourToday !== undefined) next.setHours(nextHourToday, 0, 0, 0);
    else {
      next.setDate(next.getDate() + 1);
      next.setHours(App.config.eventSlots[0], 0, 0, 0);
    }

    return next;
  },

  updateEventCountdown() {
    const element = document.getElementById("nextEventCountdown");
    if (!element) return;
    const diff = Math.max(0, App.events.getNextEventSlot() - new Date());
    const hours = Math.floor(diff / 3600000);
    const minutes = Math.floor((diff % 3600000) / 60000);
    const seconds = Math.floor((diff % 60000) / 1000);
    element.textContent = `${String(hours).padStart(2, "0")}h ${String(minutes).padStart(2, "0")}m ${String(seconds).padStart(2, "0")}s`;
  },

  renderEventSlots() {
    const element = document.getElementById("eventSlotList");
    if (!element) return;

    element.innerHTML = (App.config.eventSlots || [])
      .map(hour => `<b>${String(Number(hour)).padStart(2, "0")}h</b>`)
      .join("");
  },

  getCurrentEventSlotKey() {
    const now = new Date();
    const currentHour = now.getHours();
    const openedSlot = [...App.config.eventSlots].reverse().find(hour => hour <= currentHour);
    if (openedSlot === undefined) return "before-first-slot";
    return `${now.toISOString().slice(0, 10)}-${openedSlot}`;
  },

  async autoGenerateDueEvents() {
    const currentHour = new Date().getHours();
    const hasOpenedSlot = App.config.eventSlots.some(hour => hour <= currentHour);
    if (!hasOpenedSlot || App.state.autoEventGenerationRunning) return;

    const slotKey = App.events.getCurrentEventSlotKey();
    if (slotKey === App.state.lastAutoEventCheckKey) return;

    App.state.autoEventGenerationRunning = true;
    App.state.lastAutoEventCheckKey = slotKey;

    try {
      const data = await App.api.postToApi({ action: "generateDueEvents" });
      if (data.ok && Number(data.created || 0) > 0) {
        App.utils.setMessage(document.getElementById("eventsMessage"), data.message || "Eventos automáticos gerados.", "success");
        await App.api.loadApiData({ showLoader: false });
      }
    } catch (error) {
      console.warn("Falha ao gerar eventos automaticamente", error);
    } finally {
      App.state.autoEventGenerationRunning = false;
    }
  },

  getEventTypeClass(event) {
    const value = Number(event.ImpactoFinanceiro || 0);
    if (value > 0) return "positive";
    if (value < 0) return "negative";
    return "neutral";
  },

  getEventImpactLabel(event) {
    const value = Number(event.ImpactoFinanceiro || 0);
    if (value === 0) return event.Efeito || "Sem impacto financeiro";
    return value > 0 ? `+${App.utils.formatCurrency(value)}` : `-${App.utils.formatCurrency(Math.abs(value))}`;
  },

  isCupPrizeEvent(event) {
    const type = App.utils.normalizeText(event.Tipo || "");
    const title = App.utils.normalizeText(event.Titulo || "");
    return type === "premiacao de copa" || title.includes("premiacao por avanco") || title.includes("premiacao de campeao");
  },

  getEventDurationLabel(event) {
    const durationType = App.utils.normalizeText(event.DuracaoTipo || "");
    const affectedPlayer = String(event.JogadorAfetado || "").trim();
    const durationValue = Number(event.DuracaoValor || 0);
    const remainingMatches = Number(event.PartidasRestantes || durationValue || 0);
    const expiresAt = event.ExpiraEm ? new Date(event.ExpiraEm) : null;

    if (!affectedPlayer && !durationType && !event.ExpiraEm) return "";

    if (durationType.includes("partida")) {
      return `${affectedPlayer ? `${affectedPlayer}: ` : ""}${remainingMatches} partida(s) restante(s)`;
    }

    if (expiresAt && !Number.isNaN(expiresAt.getTime())) {
      const diff = Math.max(0, expiresAt - new Date());
      const hours = Math.floor(diff / 3600000);
      const minutes = Math.floor((diff % 3600000) / 60000);
      return `${affectedPlayer ? `${affectedPlayer}: ` : ""}${String(hours).padStart(2, "0")}h ${String(minutes).padStart(2, "0")}m restantes`;
    }

    if (durationValue) return `${affectedPlayer ? `${affectedPlayer}: ` : ""}${durationValue} ${event.DuracaoTipo || "unidade(s)"}`;
    return affectedPlayer ? `${affectedPlayer} afetado` : "";
  },

  getActiveEventsForBuyer(buyer) {
    return App.state.apiEvents.filter(event =>
      App.utils.normalizeText(event.Jogador) === App.utils.normalizeText(buyer) &&
      ["aplicado", "ativo", "gerado"].includes(App.utils.normalizeText(event.Status))
    );
  },

  renderActiveInjuriesForBuyer(buyer) {
    const injuries = App.events.getActiveEventsForBuyer(buyer).filter(event => String(event.JogadorAfetado || "").trim());
    if (!injuries.length) return "";

    return `
      <p class="legend-title" style="margin-top:12px;">Jogadores afetados</p>
      <ul class="player-list">
        ${injuries.slice(0, 4).map(event => `<li>${event.JogadorAfetado} — ${App.events.getEventDurationLabel(event)}<br><span class="calendar-muted">${event.Titulo || "Evento ativo"}</span></li>`).join("")}
      </ul>
    `;
  },



  getEventCategory(event) {
    const type = App.utils.normalizeText(event.Tipo || "");
    const title = App.utils.normalizeText(event.Titulo || "");
    const impact = Number(event.ImpactoFinanceiro || 0);
    const modifier = Number(event.ModificadorTransferencias || 0);
    const affectedPlayer = String(event.JogadorAfetado || "").trim();

    if (App.events.isCupPrizeEvent(event)) return "cup";
    if (affectedPlayer || type.includes("esportivo") || title.includes("lesao") || title.includes("desconforto")) return "injury";
    if (modifier !== 0 || type.includes("mercado") || title.includes("transfer ban") || title.includes("janela")) return "market";
    if (impact > 0) return "money-positive";
    if (impact < 0) return "money-negative";
    return "neutral";
  },

  getEventCategoryLabel(event) {
    const labels = {
      "cup": "Premiação de copa",
      "injury": "Departamento médico",
      "market": "Mercado",
      "money-positive": "Caixa positivo",
      "money-negative": "Caixa negativo",
      "neutral": "Regra da liga"
    };

    return labels[App.events.getEventCategory(event)] || "Evento";
  },

  getEventIcon(event) {
    const icons = {
      "cup": "🏆",
      "injury": "🚑",
      "market": "🔒",
      "money-positive": "💰",
      "money-negative": "⚠️",
      "neutral": "🎲"
    };

    return icons[App.events.getEventCategory(event)] || "🎲";
  },

  getEventPresentation(event) {
    const key = App.utils.normalizeText(event.Titulo || "");
    const map = {
      "venda de camisas acima do esperado": {
        title: "Camisa virou objeto de desejo",
        description: "A loja oficial foi tomada pela torcida e o caixa sorriu antes do almoço.",
        effect: "Receita extra adicionada ao orçamento."
      },
      "socio torcedor bateu meta parcial": {
        title: "Torcida passou o PIX",
        description: "A campanha de sócio-torcedor engatou e a diretoria recebeu um respiro financeiro.",
        effect: "Bônus financeiro creditado ao técnico."
      },
      "patrocinador regional ativou bonus": {
        title: "Patrocinador local abriu o cofre",
        description: "A marca apareceu bem, gostou do barulho da torcida e pagou o bônus combinado.",
        effect: "Entrada imediata no orçamento."
      },
      "camarotes esgotados": {
        title: "Camarote virou ouro",
        description: "Os ingressos premium evaporaram e o financeiro já pediu para repetir a dose.",
        effect: "Bilheteria especial creditada no orçamento."
      },
      "video do clube viralizou": {
        title: "Mascote quebrou a internet",
        description: "Um corte do clube viralizou, virou assunto no grupo e trouxe receita comercial.",
        effect: "Receita de mídia adicionada ao caixa."
      },
      "multa por atraso administrativo": {
        title: "Boleto esquecido na gaveta",
        description: "A secretaria dormiu no ponto e a liga mandou a cobrança sem dó.",
        effect: "Desconto aplicado diretamente no orçamento."
      },
      "manutencao emergencial no ct": {
        title: "CT pediu socorro",
        description: "Um reparo urgente apareceu do nada e a conta caiu no colo da diretoria.",
        effect: "Custo emergencial descontado do caixa."
      },
      "problema no gramado": {
        title: "Gramado declarou guerra",
        description: "O campo resolveu virar personagem principal e exigiu manutenção antes do próximo jogo.",
        effect: "Despesa operacional descontada do orçamento."
      },
      "janela aquecida": {
        title: "Mercado virou feira livre",
        description: "Empresários ligaram sem parar e a liga liberou um respiro para novas negociações.",
        effect: "Transferência extra liberada temporariamente."
      },
      "diretoria pediu cautela": {
        title: "Diretoria fechou a mão",
        description: "O conselho viu os números, respirou fundo e segurou a caneta das contratações.",
        effect: "Limite de transferências reduzido temporariamente."
      },
      "transfer ban relampago": {
        title: "Liga apertou o botão vermelho",
        description: "Uma pendência documental travou a mesa de inscrições e deixou o mercado em modo emergência.",
        effect: "Transferências bloqueadas temporariamente."
      },
      "desconforto muscular": {
        title: "DM pediu um minuto",
        description: "Um contratado sentiu a perna no treino e o departamento médico mandou preservar.",
        effect: "Jogador afetado fica fora pelo período indicado."
      },
      "lesao moderada": {
        title: "Treino cobrou a conta",
        description: "A intensidade passou do ponto e um jogador precisará de recuperação antes de voltar.",
        effect: "Jogador afetado fica fora pelo período indicado."
      },
      "novo patrocinador master": {
        title: "Patrocinador master chegou de helicóptero",
        description: "Uma proposta grande caiu na mesa e mudou o humor da diretoria instantaneamente.",
        effect: "Grande bônus financeiro creditado no orçamento."
      },
      "escandalo financeiro": {
        title: "Auditoria chutou a porta",
        description: "Um problema antigo veio à tona e o caixa pagou a conta da bagunça.",
        effect: "Grande desconto aplicado no orçamento."
      },
      "premiacao por avanco copa da liga": {
        title: "Prêmio de classificação",
        description: "A campanha na copa rendeu bônus esportivo pela vaga na próxima fase.",
        effect: "Premiação de copa adicionada ao orçamento."
      },
      "premiacao por avanco fa cup": {
        title: "Prêmio de classificação",
        description: "A campanha na FA Cup rendeu bônus esportivo pela vaga na próxima fase.",
        effect: "Premiação de copa adicionada ao orçamento."
      }
    };

    let item = map[key];

    if (!item && key.includes("premiacao") && key.includes("copa")) {
      item = {
        title: "Prêmio de classificação",
        description: "A classificação na copa gerou premiação esportiva para o técnico.",
        effect: "Bônus de avanço adicionado ao orçamento."
      };
    }

    return {
      title: item?.title || event.Titulo || "Evento da Liga",
      description: item?.description || event.Descricao || "A liga registrou uma ocorrência com impacto no planejamento.",
      effect: item?.effect || App.events.cleanEventEffect(event),
      category: App.events.getEventCategory(event),
      categoryLabel: App.events.getEventCategoryLabel(event),
      icon: App.events.getEventIcon(event)
    };
  },

  renderEventCard(event) {
    const presentation = App.events.getEventPresentation(event);
    const typeClass = App.events.getEventTypeClass(event);
    const color = App.data.ownerColors[event.Jogador] || App.data.ownerColors["Livre / CPU"];
    const modifier = Number(event.ModificadorTransferencias || 0);
    const durationLabel = App.events.getEventDurationLabel(event);
    const metaItems = [
      App.events.formatEventDate(event.Data),
      App.events.formatEventTime(event.Horario),
      event.Status || "Gerado"
    ].filter(Boolean);

    return `
      <article class="event-card event-card-v45 event-category-${presentation.category}" style="--event-color:${color}">
        <div class="event-card-topline">
          <span class="event-icon" aria-hidden="true">${presentation.icon}</span>
          <span class="event-category-label">${presentation.categoryLabel}</span>
          <span class="owner" style="background:${color}">${event.Jogador || "Liga"}</span>
        </div>

        <div class="event-card-header">
          <div>
            <h2>${App.utils.escapeHtml(presentation.title)}</h2>
            <p class="event-flavor">${App.utils.escapeHtml(presentation.description)}</p>
          </div>
          <span class="event-impact ${typeClass}">${App.events.getEventImpactLabel(event)}</span>
        </div>

        <div class="event-effect-box">
          <strong>Impacto</strong>
          <span>${App.utils.escapeHtml(presentation.effect)}</span>
        </div>

        <div class="event-badges">
          ${modifier !== 0 ? `<span class="limit-pill">${modifier > 0 ? "+" : ""}${modifier} transferência(s) hoje</span>` : ""}
          ${event.JogadorAfetado ? `<span class="injury-pill">🚑 ${App.utils.escapeHtml(event.JogadorAfetado)}</span>` : ""}
          ${durationLabel ? `<span class="duration-pill">${App.utils.escapeHtml(durationLabel)}</span>` : ""}
        </div>

        <div class="event-meta">${metaItems.map(App.utils.escapeHtml).join(" · ")}</div>
      </article>
    `;
  },

  getEventStats(events) {
    return {
      positive: events.filter(event => Number(event.ImpactoFinanceiro || 0) > 0).length,
      negative: events.filter(event => Number(event.ImpactoFinanceiro || 0) < 0).length,
      injuries: events.filter(event => String(event.JogadorAfetado || "").trim()).length,
      market: events.filter(event => Number(event.ModificadorTransferencias || 0) !== 0).length
    };
  },


  getEventDateTime(event) {
    const dataText = String(event.Data || "").replace(/^'/, "").trim();
    const horaText = String(event.Horario || "").replace(/^'/, "").trim();

    if (/^\d{2}\/\d{2}\/\d{4}$/.test(dataText)) {
      const [day, month, year] = dataText.split("/").map(Number);
      const [hour = 0, minute = 0] = /^\d{2}:\d{2}$/.test(horaText)
        ? horaText.split(":").map(Number)
        : [0, 0];

      return new Date(year, month - 1, day, hour, minute, 0, 0);
    }

    const timestamp = new Date(event.Timestamp || event.ExpiraEm || 0);
    if (!Number.isNaN(timestamp.getTime())) return timestamp;

    return new Date(0);
  },

  getEventSlotKey(event) {
    const date = App.events.getEventDateTime(event);

    if (Number.isNaN(date.getTime())) {
      return "";
    }

    const yyyy = date.getFullYear();
    const mm = String(date.getMonth() + 1).padStart(2, "0");
    const dd = String(date.getDate()).padStart(2, "0");
    const hh = String(date.getHours()).padStart(2, "0");

    return `${yyyy}-${mm}-${dd}-${hh}`;
  },

  isActiveOrDurationEvent(event) {
    const status = App.utils.normalizeText(event.Status);
    const hasDuration = Boolean(event.ExpiraEm || event.DuracaoTipo || event.JogadorAfetado);
    const expiresAt = event.ExpiraEm ? new Date(event.ExpiraEm) : null;
    const stillInTime = expiresAt && !Number.isNaN(expiresAt.getTime()) ? expiresAt >= new Date() : false;
    const remainingMatches = Number(event.PartidasRestantes || 0);

    return status === "ativo" || stillInTime || remainingMatches > 0 || (hasDuration && status !== "encerrado");
  },

  getLatestEventSlotKey(events) {
    const keys = events
      .map(event => App.events.getEventSlotKey(event))
      .filter(Boolean)
      .sort();

    return keys.length ? keys[keys.length - 1] : "";
  },

  getFilteredEvents() {
    const search = App.utils.normalizeText(document.getElementById("eventsSearchInput")?.value);
    const owner = document.getElementById("eventsOwnerFilter")?.value || "all";
    const type = document.getElementById("eventsTypeFilter")?.value || "all";
    const period = document.getElementById("eventsPeriodFilter")?.value || "latest";

    let events = [...App.state.apiEvents];
    const dynamicEvents = events.filter(event => !App.events.isCupPrizeEvent(event));

    if (period === "latest") {
      const latestKey = App.events.getLatestEventSlotKey(dynamicEvents);
      events = latestKey ? dynamicEvents.filter(event => App.events.getEventSlotKey(event) === latestKey) : dynamicEvents;
    } else if (period === "active") {
      events = dynamicEvents.filter(event => App.events.isActiveOrDurationEvent(event));
    } else if (period === "today") {
      const todayText = new Date().toLocaleDateString("pt-BR");
      events = events.filter(event => App.events.formatEventDate(event.Data || event.Timestamp) === todayText);
    }

    events = events
      .filter(event => owner === "all" || event.Jogador === owner)
      .filter(event => type === "all" || App.events.getEventTypeClass(event) === type)
      .filter(event => {
        if (!search) return true;
        return App.utils.normalizeText(`${event.Jogador} ${event.Titulo} ${event.Descricao} ${event.Efeito} ${event.Tipo} ${event.JogadorAfetado}`).includes(search);
      })
      .sort((a, b) => App.events.getEventDateTime(b) - App.events.getEventDateTime(a));

    if (period === "last12") {
      events = events.slice(0, 12);
    }

    if (period === "all" && !search) {
      events = events.slice(0, 120);
    }

    return events;
  },


  formatEventDate(value) {
    if (!value) return "";
    const text = String(value || "").replace(/^'/, "").trim();
    if (/^\d{2}\/\d{2}\/\d{4}$/.test(text)) return text;
    const date = new Date(text);
    if (!Number.isNaN(date.getTime())) return date.toLocaleDateString("pt-BR");
    return text;
  },

  formatEventTime(value) {
    if (!value) return "";
    const text = String(value || "").replace(/^'/, "").trim();
    if (/^\d{2}:\d{2}$/.test(text)) return text;
    const date = new Date(text);
    if (!Number.isNaN(date.getTime()) && date.getFullYear() < 2000) {
      return date.toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" });
    }
    return text;
  },

  cleanEventEffect(event) {
    const effect = String(event.Efeito || "").trim();
    if (effect && effect !== "#ERROR!") return effect;

    const modifier = Number(event.ModificadorTransferencias || 0);
    if (modifier > 0) return `Libera ${modifier} transferência(s) extra hoje.`;
    if (modifier < 0) return `Reduz ${Math.abs(modifier)} transferência(s) hoje.`;

    return "Sem efeito adicional.";
  },

  render() {
    App.events.renderEventSlots();
    App.events.updateEventCountdown();

    const summary = document.getElementById("eventsSummary");
    const grid = document.getElementById("eventsGrid");
    if (!summary || !grid) return;

    const todayText = new Date().toLocaleDateString("pt-BR");
    const dynamicEvents = App.state.apiEvents.filter(event => !App.events.isCupPrizeEvent(event));
    const todayEvents = dynamicEvents.filter(event => App.events.formatEventDate(event.Data || event.Timestamp) === todayText);
    const activeEvents = dynamicEvents.filter(event => App.events.isActiveOrDurationEvent(event));
    const totalImpact = App.state.apiEvents.reduce((sum, event) => sum + Number(event.ImpactoFinanceiro || 0), 0);
    const lastSlot = Math.max(...App.config.eventSlots.map(Number));
    const pendingSlots = Math.max(0, (App.config.eventSlots.length * App.utils.getHumanBuyers().length) - todayEvents.length);

    summary.classList.add("events-summary-v45");
    summary.innerHTML = `
      ${App.ui.summaryCard("Última rodada", todayEvents.length, "eventos dinâmicos hoje", "event-summary-main")}
      ${App.ui.summaryCard("Ativos agora", activeEvents.length, "lesões, mercado ou duração")}
      ${App.ui.summaryCard("Impacto líquido", App.utils.formatCurrency(totalImpact), "somando histórico carregado")}
      ${App.ui.summaryCard("Slots restantes", pendingSlots, `até ${String(lastSlot).padStart(2, "0")}h`)}
    `;

    const events = App.events.getFilteredEvents();
    const stats = App.events.getEventStats(events);
    const periodSelect = document.getElementById("eventsPeriodFilter");
    const periodLabel = periodSelect ? periodSelect.options[periodSelect.selectedIndex]?.textContent : "Eventos filtrados";

    const activeFilteredEvents = events.filter(event => App.events.isActiveOrDurationEvent(event)).slice(0, 4);

    grid.innerHTML = events.length ? `
      <section class="event-workspace">
        <section class="event-board-header event-board-header-v66">
          <div>
            <span class="modal-kicker">Mesa de controle</span>
            <strong>${periodLabel}</strong>
            <span>${events.length} ocorrência(s) na tela, organizadas por impacto, técnico e duração.</span>
          </div>
          <div class="event-mini-stats">
            <span>Caixa +${stats.positive}</span>
            <span>Risco ${stats.negative}</span>
            <span>DM ${stats.injuries}</span>
            <span>Mercado ${stats.market}</span>
          </div>
        </section>

        <section class="event-focus-strip">
          <article>
            <span>Ativos</span>
            <strong>${activeFilteredEvents.length}</strong>
            <small>${activeFilteredEvents.length ? activeFilteredEvents.map(event => `${event.Jogador || "Liga"}: ${event.Titulo || "Evento ativo"}`).join(" · ") : "Nenhuma duração ativa no filtro atual."}</small>
          </article>
          <article>
            <span>Financeiro</span>
            <strong>${stats.positive + stats.negative}</strong>
            <small>${stats.positive} positivo(s), ${stats.negative} negativo(s)</small>
          </article>
          <article>
            <span>DM / Mercado</span>
            <strong>${stats.injuries + stats.market}</strong>
            <small>${stats.injuries} lesão(ões), ${stats.market} trava(s)</small>
          </article>
        </section>

        <section class="event-card-grid-v45 event-card-grid-v66">
          ${events.map(event => App.events.renderEventCard(event)).join("")}
        </section>
      </section>
    ` : `
      <article class="event-empty-v45">
        <strong>Nenhum evento encontrado</strong>
        <p>Troque o período, remova filtros ou pesquise por técnico, jogador, punição, premiação ou impacto financeiro.</p>
      </article>
    `;
  }
};
