window.App = window.App || {};

App.events = {
  getNextEventSlot() {
    const now = new Date();
    const currentHour = now.getHours() + now.getMinutes() / 60 + now.getSeconds() / 3600;
    const nextHourToday = App.config.eventSlots.find(hour => hour > currentHour);
    const next = new Date(now);

    if (nextHourToday !== undefined) next.setHours(nextHourToday, 0, 0, 0);
    else {
      next.setDate(next.getDate() + 1);
      next.setHours(App.config.eventSlots[0], 0, 0, 0);
    }

    return next;
  },

  updateEventCountdown() {
    const element = document.getElementById("nextEventCountdown");
    if (!element) return;
    const diff = Math.max(0, App.events.getNextEventSlot() - new Date());
    const hours = Math.floor(diff / 3600000);
    const minutes = Math.floor((diff % 3600000) / 60000);
    const seconds = Math.floor((diff % 60000) / 1000);
    element.textContent = `${String(hours).padStart(2, "0")}h ${String(minutes).padStart(2, "0")}m ${String(seconds).padStart(2, "0")}s`;
  },

  getCurrentEventSlotKey() {
    const now = new Date();
    const currentHour = now.getHours();
    const openedSlot = [...App.config.eventSlots].reverse().find(hour => hour <= currentHour);
    if (openedSlot === undefined) return "before-first-slot";
    return `${now.toISOString().slice(0, 10)}-${openedSlot}`;
  },

  async autoGenerateDueEvents() {
    const currentHour = new Date().getHours();
    const hasOpenedSlot = App.config.eventSlots.some(hour => hour <= currentHour);
    if (!hasOpenedSlot || App.state.autoEventGenerationRunning) return;

    const slotKey = App.events.getCurrentEventSlotKey();
    if (slotKey === App.state.lastAutoEventCheckKey) return;

    App.state.autoEventGenerationRunning = true;
    App.state.lastAutoEventCheckKey = slotKey;

    try {
      const data = await App.api.postToApi({ action: "generateDueEvents" });
      if (data.ok && Number(data.created || 0) > 0) {
        App.utils.setMessage(document.getElementById("eventsMessage"), data.message || "Eventos automáticos gerados.", "success");
        await App.api.loadApiData();
      }
    } catch (error) {
      console.warn("Falha ao gerar eventos automaticamente", error);
    } finally {
      App.state.autoEventGenerationRunning = false;
    }
  },

  getEventTypeClass(event) {
    const value = Number(event.ImpactoFinanceiro || 0);
    if (value > 0) return "positive";
    if (value < 0) return "negative";
    return "neutral";
  },

  getEventImpactLabel(event) {
    const value = Number(event.ImpactoFinanceiro || 0);
    if (value === 0) return event.Efeito || "Sem impacto financeiro";
    return value > 0 ? `+${App.utils.formatCurrency(value)}` : `-${App.utils.formatCurrency(Math.abs(value))}`;
  },

  getEventDurationLabel(event) {
    const durationType = App.utils.normalizeText(event.DuracaoTipo || "");
    const affectedPlayer = String(event.JogadorAfetado || "").trim();
    const durationValue = Number(event.DuracaoValor || 0);
    const remainingMatches = Number(event.PartidasRestantes || durationValue || 0);
    const expiresAt = event.ExpiraEm ? new Date(event.ExpiraEm) : null;

    if (!affectedPlayer && !durationType && !event.ExpiraEm) return "";

    if (durationType.includes("partida")) {
      return `${affectedPlayer ? `${affectedPlayer}: ` : ""}${remainingMatches} partida(s) restante(s)`;
    }

    if (expiresAt && !Number.isNaN(expiresAt.getTime())) {
      const diff = Math.max(0, expiresAt - new Date());
      const hours = Math.floor(diff / 3600000);
      const minutes = Math.floor((diff % 3600000) / 60000);
      return `${affectedPlayer ? `${affectedPlayer}: ` : ""}${String(hours).padStart(2, "0")}h ${String(minutes).padStart(2, "0")}m restantes`;
    }

    if (durationValue) return `${affectedPlayer ? `${affectedPlayer}: ` : ""}${durationValue} ${event.DuracaoTipo || "unidade(s)"}`;
    return affectedPlayer ? `${affectedPlayer} afetado` : "";
  },

  getActiveEventsForBuyer(buyer) {
    return App.state.apiEvents.filter(event =>
      App.utils.normalizeText(event.Jogador) === App.utils.normalizeText(buyer) &&
      ["aplicado", "ativo", "gerado"].includes(App.utils.normalizeText(event.Status))
    );
  },

  renderActiveInjuriesForBuyer(buyer) {
    const injuries = App.events.getActiveEventsForBuyer(buyer).filter(event => String(event.JogadorAfetado || "").trim());
    if (!injuries.length) return "";

    return `
      <p class="legend-title" style="margin-top:12px;">Jogadores afetados</p>
      <ul class="player-list">
        ${injuries.slice(0, 4).map(event => `<li>${event.JogadorAfetado} — ${App.events.getEventDurationLabel(event)}<br><span class="calendar-muted">${event.Titulo || "Evento ativo"}</span></li>`).join("")}
      </ul>
    `;
  },

  getFilteredEvents() {
    const search = App.utils.normalizeText(document.getElementById("eventsSearchInput")?.value);
    const owner = document.getElementById("eventsOwnerFilter")?.value || "all";
    const type = document.getElementById("eventsTypeFilter")?.value || "all";

    return [...App.state.apiEvents]
      .filter(event => owner === "all" || event.Jogador === owner)
      .filter(event => type === "all" || App.events.getEventTypeClass(event) === type)
      .filter(event => {
        if (!search) return true;
        return App.utils.normalizeText(`${event.Jogador} ${event.Titulo} ${event.Descricao} ${event.Efeito} ${event.Tipo} ${event.JogadorAfetado}`).includes(search);
      })
      .sort((a, b) => new Date(b.Timestamp || 0) - new Date(a.Timestamp || 0));
  },

  render() {
    App.events.updateEventCountdown();

    const summary = document.getElementById("eventsSummary");
    const grid = document.getElementById("eventsGrid");
    if (!summary || !grid) return;

    const todayText = new Date().toLocaleDateString("pt-BR");
    const todayEvents = App.state.apiEvents.filter(event => String(event.Data || "") === todayText || new Date(event.Timestamp || 0).toLocaleDateString("pt-BR") === todayText);
    const totalImpact = App.state.apiEvents.reduce((sum, event) => sum + Number(event.ImpactoFinanceiro || 0), 0);
    const pendingSlots = Math.max(0, (App.config.eventSlots.length * App.utils.getHumanBuyers().length) - todayEvents.length);

    summary.innerHTML = `
      <article class="summary-card"><span>Eventos hoje</span><strong>${todayEvents.length}</strong></article>
      <article class="summary-card"><span>Faltam hoje</span><strong>${pendingSlots}</strong></article>
      <article class="summary-card"><span>Impacto total</span><strong>${App.utils.formatCurrency(totalImpact)}</strong></article>
      <article class="summary-card"><span>Horários</span><strong>05h-23h</strong></article>
    `;

    const events = App.events.getFilteredEvents();
    grid.innerHTML = events.length ? events.map(event => {
      const typeClass = App.events.getEventTypeClass(event);
      const color = App.data.ownerColors[event.Jogador] || App.data.ownerColors["Livre / CPU"];
      const modifier = Number(event.ModificadorTransferencias || 0);
      return `
        <article class="event-card" style="--event-color:${color}">
          <div class="event-card-header">
            <div><h2>${event.Titulo || "Evento"}</h2><span class="owner" style="background:${color}">${event.Jogador || "Liga"}</span></div>
            <span class="event-impact ${typeClass}">${App.events.getEventImpactLabel(event)}</span>
          </div>
          <p>${event.Descricao || "Sem descrição."}</p>
          <p><strong>Efeito:</strong> ${event.Efeito || "Sem efeito adicional."}</p>
          ${modifier !== 0 ? `<span class="limit-pill">${modifier > 0 ? "+" : ""}${modifier} transferência(s) hoje</span>` : ""}
          ${event.JogadorAfetado ? `<span class="injury-pill">${event.JogadorAfetado} afetado</span>` : ""}
          ${App.events.getEventDurationLabel(event) ? `<div class="event-timer"><strong>Duração do efeito</strong>${App.events.getEventDurationLabel(event)}</div>` : ""}
          <div class="event-meta">${event.Data || ""} · ${event.Horario || ""} · ${event.Tipo || "Evento"} · ${event.Status || "Gerado"}</div>
        </article>
      `;
    }).join("") : `<article class="event-card"><h2>Nenhum evento encontrado</h2><p>Os eventos serão gerados automaticamente quando os horários forem abertos.</p></article>`;
  }
};
