window.App = window.App || {};

App.main = {
  renderAll() {
    App.standings.render();
    App.calendar.render();
    App.cups.render();
    App.events.render();
    App.players.render();
    App.transfers.render();
    App.forms.renderApiSummary();
  },

  setupTabs() {
    document.querySelectorAll(".tab-button").forEach(button => {
      button.addEventListener("click", () => {
        document.querySelectorAll(".tab-button").forEach(item => item.classList.remove("active"));
        document.querySelectorAll(".view").forEach(view => view.classList.remove("active"));
        button.classList.add("active");
        document.getElementById(button.dataset.view)?.classList.add("active");
      });
    });
  },

  setupFilters() {
    [
      "calendarSearchInput", "calendarCompetitionFilter", "calendarWeekFilter",
      "cupsSearchInput", "cupsCompetitionFilter",
      "playersSearchInput", "playersFilter",
      "eventsSearchInput", "eventsOwnerFilter", "eventsTypeFilter",
      "transferSearchInput", "transferOwnerFilter", "transferStatusFilter"
    ].forEach(id => {
      const element = document.getElementById(id);
      if (!element) return;
      const eventName = element.tagName === "INPUT" ? "input" : "change";
      element.addEventListener(eventName, App.main.renderAll);
    });
  },

  updateTransferCountdown() {
    const element = document.getElementById("nextTransferCountdown");
    if (!element) return;
    const now = new Date();
    const nextReset = new Date(now);
    nextReset.setHours(24, 0, 0, 0);
    const diff = Math.max(0, nextReset - now);
    const hours = Math.floor(diff / 3600000);
    const minutes = Math.floor((diff % 3600000) / 60000);
    const seconds = Math.floor((diff % 60000) / 1000);
    element.textContent = `${String(hours).padStart(2, "0")}h ${String(minutes).padStart(2, "0")}m ${String(seconds).padStart(2, "0")}s`;
  },

  startTimers() {
    App.main.updateTransferCountdown();
    App.events.updateEventCountdown();

    setInterval(() => {
      App.main.updateTransferCountdown();
      App.events.updateEventCountdown();
      App.main.renderAll();
    }, 1000);

    setInterval(App.events.autoGenerateDueEvents, 60000);
  },

  init() {
    App.main.setupTabs();
    App.forms.populateTeamOptions();
    App.forms.setupForms();
    App.main.setupFilters();
    App.calendar.populateWeeks();
    App.main.renderAll();
    App.main.startTimers();

    App.api.loadApiData()
      .then(App.events.autoGenerateDueEvents)
      .catch(() => {});
  }
};

document.addEventListener("DOMContentLoaded", App.main.init);
