window.App = window.App || {};

App.main = {
  renderAll() {
    App.standings.render();
    App.calendar.render();
    App.cups.render();
    App.events.render();
    App.players.render();
    App.transfers.render();
    App.forms.renderApiSummary();
  },

  showLoader(title = "Carregando dados da liga", message = "Aguarde enquanto a classificação, o calendário e os painéis são atualizados.") {
    const overlay = document.getElementById("globalLoader");
    if (!overlay) return;
    const titleEl = document.getElementById("globalLoaderTitle");
    const textEl = document.getElementById("globalLoaderText");

    App.state.loadingCount = Number(App.state.loadingCount || 0) + 1;
    if (titleEl) titleEl.textContent = title;
    if (textEl) textEl.textContent = message;
    overlay.classList.add("is-visible");
    document.body.classList.add("loader-active");
  },

  hideLoader(force = false) {
    const overlay = document.getElementById("globalLoader");
    if (!overlay) return;

    if (force) App.state.loadingCount = 0;
    else App.state.loadingCount = Math.max(0, Number(App.state.loadingCount || 0) - 1);

    if (App.state.loadingCount > 0) return;

    overlay.classList.remove("is-visible");
    document.body.classList.remove("loader-active");
  },

  setupTabs() {
    document.querySelectorAll(".tab-button").forEach(button => {
      button.addEventListener("click", () => {
        document.querySelectorAll(".tab-button").forEach(item => item.classList.remove("active"));
        document.querySelectorAll(".view").forEach(view => view.classList.remove("active"));
        button.classList.add("active");
        document.getElementById(button.dataset.view)?.classList.add("active");
      });
    });
  },

  setupFilters() {
    [
      "calendarSearchInput", "calendarCompetitionFilter", "calendarOwnerFilter", "calendarWeekFilter", "calendarStatusFilter",
      "cupsSearchInput", "cupsCompetitionFilter",
      "playersSearchInput", "playersFilter",
      "eventsSearchInput", "eventsOwnerFilter", "eventsTypeFilter", "eventsPeriodFilter",
      "transferSearchInput", "transferOwnerFilter", "transferStatusFilter"
    ].forEach(id => {
      const element = document.getElementById(id);
      if (!element) return;
      const eventName = element.tagName === "INPUT" ? "input" : "change";
      element.addEventListener(eventName, App.main.renderAll);
    });
  },

  updateTransferCountdown() {
    const element = document.getElementById("nextTransferCountdown");
    if (!element) return;
    const now = new Date();
    const nextReset = new Date(now);
    nextReset.setHours(24, 0, 0, 0);
    const diff = Math.max(0, nextReset - now);
    const hours = Math.floor(diff / 3600000);
    const minutes = Math.floor((diff % 3600000) / 60000);
    const seconds = Math.floor((diff % 60000) / 1000);
    element.textContent = `${String(hours).padStart(2, "0")}h ${String(minutes).padStart(2, "0")}m ${String(seconds).padStart(2, "0")}s`;
  },

  startTimers() {
    App.main.updateTransferCountdown();
    App.events.updateEventCountdown();

    setInterval(() => {
      App.main.updateTransferCountdown();
      App.events.updateEventCountdown();
      if (App.state.apiLoaded) App.main.renderAll();
    }, 1000);

    setInterval(App.events.autoGenerateDueEvents, 60000);
  },

  init() {
    App.main.setupTabs();
    App.forms.populateTeamOptions();
    App.forms.setupForms();
    App.main.setupFilters();
    App.calendar.populateWeeks();
    App.main.startTimers();

    App.api.loadApiData({
      title: "Carregando dados da liga",
      message: "Consultando a planilha e preparando classificação, calendário, copas, eventos e painel."
    })
      .then(App.events.autoGenerateDueEvents)
      .catch(() => {});
  }
};

document.addEventListener("DOMContentLoaded", App.main.init);
