-- v91 - Do not write generated final_value in transfer RPCs.
-- final_value is generated by the database from market_value + overall_rate.
-- The app still needs the calculated value for validation and API responses,
-- but inserts must let PostgreSQL use the generated/default column value.

do $$
declare
  v_function_sql text;
  v_next_sql text;
begin
  v_function_sql := pg_get_functiondef(
    'public.app_add_transfer_verified_salary(text,text,text,text,text,integer,numeric,numeric,text,text)'::regprocedure
  );

  v_next_sql := replace(
    v_function_sql,
    E'    overall_rate,\n    final_value,\n    weekly_salary_eur,',
    E'    overall_rate,\n    weekly_salary_eur,'
  );

  v_next_sql := replace(
    v_next_sql,
    E'    v_rate,\n    v_final_value,\n    v_weekly_salary,',
    E'    v_rate,\n    v_weekly_salary,'
  );

  if v_next_sql <> v_function_sql then
    execute v_next_sql;
  else
    raise notice 'app_add_transfer_verified_salary already avoids generated final_value inserts.';
  end if;

  v_function_sql := pg_get_functiondef(
    'public.app_add_transfer_with_trade_verified_salary(text,text,text,text,text,integer,numeric,text,numeric,numeric,text,text)'::regprocedure
  );

  v_next_sql := replace(
    v_function_sql,
    E'    overall_rate,\n    final_value,\n    weekly_salary_eur,',
    E'    overall_rate,\n    weekly_salary_eur,'
  );

  v_next_sql := replace(
    v_next_sql,
    E'    v_rate,\n    v_gross_value,\n    v_weekly_salary,',
    E'    v_rate,\n    v_weekly_salary,'
  );

  v_next_sql := replace(
    v_next_sql,
    E'      overall_rate,\n      final_value,\n      status,',
    E'      overall_rate,\n      status,'
  );

  if v_next_sql <> v_function_sql then
    execute v_next_sql;
  else
    raise notice 'app_add_transfer_with_trade_verified_salary already avoids generated final_value inserts.';
  end if;
end $$;
